export const nobitexSymbolsRial =
    ['BTCIRT', 'ETHIRT', 'LTCIRT', 'USDTIRT', 'XRPIRT', 'BCHIRT', 'BNBIRT', 'EOSIRT', 'XLMIRT', 'ETCIRT', 'TRXIRT', 'DOGEIRT', 'UNIIRT', 'DAIIRT', 'LINKIRT', 'DOTIRT', 'AAVEIRT', 'ADAIRT', 'SHIBIRT', 'FTMIRT', 'MATICIRT', 'AXSIRT', 'MANAIRT', 'SANDIRT', 'AVAXIRT', 'MKRIRT', 'GMTIRT', 'USDCIRT']


export const nobitexSymbolsUSDT =
    [
        "BTCUSDT",
        "ETHUSDT",
        "ETCUSDT",
        "DOGEUSDT",
        "ADAUSDT",
        "BCHUSDT",
        "LTCUSDT",
        "BNBUSDT",
        "EOSUSDT",
        "XLMUSDT",
        "XRPUSDT",
        "TRXUSDT",
        "UNIUSDT",
        "LINKUSDT",
        "DAIUSDT",
        "DOTUSDT",
        "SHIBUSDT",
        "AAVEUSDT",
        "FTMUSDT",
        "MATICUSDT",
        "AXSUSDT",
        "MANAUSDT",
        "SANDUSDT",
        "AVAXUSDT",
        "USDCUSDT",
        "GMTUSDT",
        "MKRUSDT",
        "SOLUSDT",
        "ATOMUSDT",
        "GRTUSDT",
        "BATUSDT",
        "NEARUSDT",
        "APEUSDT",
        "QNTUSDT",
        "CHZUSDT",
        "XMRUSDT",
        "EGALAUSDT",
        "BUSDUSDT",
        "ALGOUSDT",
        "HBARUSDT",
        "1INCHUSDT",
        "YFIUSDT",
        "FLOWUSDT",
        "SNXUSDT",
        "ENJUSDT",
        "CRVUSDT",
        "FILUSDT",
        "WBTCUSDT",
        "LDOUSDT",
        "DYDXUSDT",
        "APTUSDT",
        "MASKUSDT",
        "COMPUSDT",
        "BALUSDT",
        "LRCUSDT",
        "LPTUSDT",
        "ENSUSDT",
        "SUSHIUSDT",
        "API3USDT",
        "ONEUSDT",
        "GLMUSDT",
        "PMNUSDT",
        "DAOUSDT",
        "CVCUSDT",
        "NMRUSDT",
        "STORJUSDT",
        "SNTUSDT",
        "ANTUSDT",
        "ZRXUSDT",
        "SLPUSDT",
        "EGLDUSDT",
        "IMXUSDT",
        "BLURUSDT",
        "100K_FLOKIUSDT",
        // "1B_BABYDOGEUSDT", Low 24Valume
        "1M_NFTUSDT",
        "1M_BTTUSDT",
        "TUSDT",
        "CELRUSDT",
        "ARBUSDT",
        "MAGICUSDT",
        "GMXUSDT",
        "BANDUSDT",
        "CVXUSDT",
        "TONUSDT",
        "SSVUSDT",
        "MDTUSDT",
        "OMGUSDT",
        "WLDUSDT",
        "RDNTUSDT",
        "JSTUSDT",
        "BICOUSDT",
        "RNDRUSDT",
        "WOOUSDT",
        "SKLUSDT",
        "GALUSDT",
        "AGIXUSDT",
        "FETUSDT",
        "ILVUSDT",
        "XTZUSDT",
        "AGLDUSDT",
        "TRBUSDT",
        "RSRUSDT"
    ]

// ['BTCUSDT', 'ETHUSDT', 'LTCUSDT', 'XRPUSDT', 'BCHUSDT', 'BNBUSDT', 'EOSUSDT', 'XLMUSDT', 'ETCUSDT', 'TRXUSDT', 'PMNUSDT', 'DOGEUSDT', 'UNIUSDT', 'DAIUSDT', 'LINKUSDT', 'DOTUSDT', 'AAVEUSDT', 'ADAUSDT', 'SHIBUSDT', 'FTMUSDT', 'MATICUSDT', 'AXSUSDT', 'MANAUSDT', 'SANDUSDT', 'AVAXUSDT', 'MKRUSDT', 'GMTUSDT', 'USDCUSDT', 'GLMUSDT', 'JSTUSDT', 'CVXUSDT', 'FETUSDT']


export const nobitexUsdTSymbols = () => 'btc,eth,etc,doge,ada,bch,ltc,bnb,eos,xlm,xrp,trx,uni,link,dai,dot,shib,aave,ftm,matic,axs,mana,sand,avax,usdc,gmt,mkr,sol,atom,grt,bat,near,ape,qnt,chz,xmr,egala,busd,algo,hbar,1inch,yfi,flow,snx,enj,crv,fil,wbtc,ldo,dydx,apt,mask,comp,bal,lrc,lpt,ens,sushi,api3,one,glm,pmn,dao,cvc,nmr,storj,snt,ant,zrx,slp,egld,imx,blur,100k_floki,1b_babydoge,1m_nft,1m_btt,t,celr,arb,magic,gmx,band,cvx,ton,ssv,mdt,omg,wld,rdnt,jst,bico,rndr,woo,skl,gal,agix,fet,ilv,xtz,agld,trb,rsr'.split(',').map(i => i.toUpperCase().concat('USDT'))


export type nobitexSymbolsTypes =
    'BTCIRT' | 'ETHIRT' | 'LTCIRT' | 'USDTIRT' | 'XRPIRT' | 'BCHIRT' | 'BNBIRT' | 'EOSIRT' | 'XLMIRT' | 'ETCIRT' | 'TRXIRT' | 'DOGEIRT' | 'UNIIRT' | 'DAIIRT' | 'LINKIRT' | 'DOTIRT' | 'AAVEIRT' | 'ADAIRT' | 'SHIBIRT' | 'FTMIRT' | 'MATICIRT' | 'AXSIRT' | 'MANAIRT' | 'SANDIRT' | 'AVAXIRT' | 'MKRIRT' | 'GMTIRT' | 'USDCIRT' | 'BTCUSDT' | 'ETHUSDT' | 'LTCUSDT' | 'XRPUSDT' | 'BCHUSDT' | 'BNBUSDT' | 'EOSUSDT' | 'XLMUSDT' | 'ETCUSDT' | 'TRXUSDT' | 'PMNUSDT' | 'DOGEUSDT' | 'UNIUSDT' | 'DAIUSDT' | 'LINKUSDT' | 'DOTUSDT' | 'AAVEUSDT' | 'ADAUSDT' | 'SHIBUSDT' | 'FTMUSDT' | 'MATICUSDT' | 'AXSUSDT' | 'MANAUSDT' | 'SANDUSDT' | 'AVAXUSDT' | 'MKRUSDT' | 'GMTUSDT' | 'USDCUSDT'


export const TETTER_TRADE_WAGE_PERCENT = 0.00182